export const PORTFOLIO_MAX_EDGE_PIXELS = 3000;
export const AVATAR_MAX_EDGE_PIXELS = 1200;
export const REFERENCE_MAX_EDGE_PIXELS = 1600;
export const NORMALIZED_JPEG_QUALITY = 88;
export const NORMALIZED_OUTPUT_FORMAT = "image/jpeg";
export const NORMALIZED_FILE_EXTENSION = "jpg";