import {
  type RouteConfig,
  route,
  index,
  prefix,
} from "@react-router/dev/routes";

export default [
 ...prefix("/:lang?", [
    index("routes/home/home.tsx"),
    route("artists", "routes/artists/artists.tsx"),
    route("artists/:slug", "routes/artistPage/artists.$slug.tsx"),
    route("media/*", "routes/media.$.tsx"),
    route("booking", "routes/booking.tsx"),
    route("api/booking-photos", "routes/api.booking-photos.ts"),
    route("piercing", "routes/piercing/piercing.tsx"),
    route("aftercare", "routes/aftercare/aftercare.tsx"),
    route("aftercare/aftercarePiercing", "routes/aftercare/aftercarePiercing/aftercarePiercing.tsx"),
    route("aftercare/aftercareTattoo", "routes/aftercare/aftercareTattoo/aftercareTattoo.tsx"),
    route("flashdesigns", "./routes/flashdesigns/flashdesigns.tsx"),
    route("tattoostyles", "routes/tattoostyles/tattoostyles.tsx"),
    route("faq", "routes/faq/faq.tsx"),
    route("coupon", "routes/coupon/coupon.tsx"),
    route("privacypolicy", "routes/privacypolicy/privacypolicy.tsx"),
    route("portfolio-image/*", "routes/portfolio-image.$.tsx"),
  ]),
    route("admin", "routes/admin.tsx", [
    index("routes/admin._index.tsx"),
    route("me", "routes/admin.me.tsx"),
    route("me/photos", "routes/admin.me.photos.tsx"),
    route("me/flash", "routes/admin.me.flash.tsx"),
    route("landing", "routes/admin.landing.tsx"),
    route("flash", "routes/admin.flash.tsx"),
    route("artists/new", "routes/admin.artists.new.tsx"),
    route("artists/:id", "routes/admin.artists.$id.tsx"),
    route("artists/:id/delete", "routes/admin.artists.$id.delete.tsx"),
    route("artists/:id/photos", "routes/admin.artists.$id.photos.tsx"),
    route("artists/:id/flash", "routes/admin.artists.$id.flash.tsx"),
    route("api/artist-photos", "routes/admin.api.artist-photos.ts"),
    route("api/artist-avatar", "routes/admin.api.artist-avatar.ts"),
    route("api/artist-photos/reorder", "routes/admin.api.artist-photos.reorder.ts"),
    route("api/artist-photos/delete", "routes/admin.api.artist-photos.delete.ts"),
    route("api/artist-photos/style", "routes/admin.api.artist-photos.style.ts"),
    route("api/curate-gallery", "routes/admin.api.curate-gallery.ts"),
    route("api/reorder-roster", "routes/admin.api.reorder-roster.ts"),
  ]),
] satisfies RouteConfig;
